### PR TITLE
Supporting SyndCategory label

### PR DESCRIPTION
**Pull request by bgrotan**
With this patch, categories in Atom Feeds now supports labels. 
Supporting labels in categories was marked as TODO in the previous source code.

Example:
SyndCategory crsCategory = new SyndCategoryImpl();
crsCategory.setName("EPSG:4258");
crsCategory.setTaxonomyUri("http://www.opengis.net/def/crs/");
crsCategory.setLabel("EPSG/0/4258");

results in:
&LT;category term="EPSG:4258" scheme="http://www.opengis.net/def/crs/" label="EPSG/0/4258"/>

### CODE REVIEW

**Comment by mishako** [comment]
@bgrotan Thank you for the contribution! I'm curious about `DCSubject` changes - are those related? Does it not work without changes to Dublin Core module?

**Comment by bgrotan** [comment]
Thanks for responding. I have to get back to you on that topic.

**Comment by tfunq** [comment]
Can this be merged into master and released? Category label is mandatory for inspire atom feeds.

**Comment by mishako** [comment]
@tfunq I'm not sure about `DCSubject` changes (see my previous comment). Otherwise I would gladly merge it in.

**Comment by nivekuil** [comment]
I'd like to see this merged as well! It looks like the unrelated changes have been removed.

**Comment by PatrickGotthard** [comment]
Version 1.16.0 is on its way to Maven Central.
It should be available soon.

**Pull request merged**
