### PR TITLE
Update project URL in POM

### PR DESCRIPTION
**Pull request by makigumo**
The old link is pointing to some unrelated Chinese website.

### CODE REVIEW

**Comment by PatrickGotthard** [comment]
Hi @makigumo,

thanks for your contribution. Unfortunately the GitHub Pages will be deleted soon because I'm working on a new documentation (see #498). So either we should link

- the new documentation https://rome.readthedocs.io/en/latest
- or the main repository page https://github.com/rometools/rome

Regards,
Patrick

**Comment by makigumo** [comment]
Thank you for your feedback.
I have updated the link to point to the new documentation page. I went with https://rome.readthedocs.io/ which redirects to https://rome.readthedocs.io/en/latest and https://github.com/rometools/rome is already set as scm-url. I hope this is fine.

**Comment by PatrickGotthard** [comment]
Hi @makigumo,

I prefer to use https://github.com/rometools/rome as main homepage.
Please update your PR accordingly and I' ll add a link to the new documentation as soon as it's ready.

Regards,
Patrick

**Comment by makigumo** [comment]
Understood. I updated accordingly.

**Pull request merged**
