### PR TITLE
Bump Java from 6 to 11

### PR DESCRIPTION
**Pull request by PatrickGotthard**

### CODE REVIEW

**Comment by fschiettecatte** [comment]
Hi, any reason why 11 as opposed to 8 which seems to be the release that most projects/libraries support?

**Comment by PatrickGotthard** [comment]
Hi @fschiettecatte,

since there are so many JDK vendors out there it was hard for me to find the correct EOL date for the OpenJDK project.

I researched again and according to https://adoptium.net/de/support/ Java 8 will be supported longer than Java 11. I wanted to align with the oldest "officially" supported OpenJDK but it seems that I made my decided based on wrong informations.

I'll think about support for Java 8 again. There shouldn't be much (if any) code that relies on Java 11.

Regards,
Patrick

**Comment by fschiettecatte** [comment]
Hi @PatrickGotthard

Not to belabor this, I did a quick check of the various Apache and Apache Commons projects and the preponderance support Java 8 as the minimum platform. Also Java 8 is the default version on RHEL 7 & 8 (and clones). So I think there is a good argument for supporting that instead of Java 11.

Cheers
François

**Comment by PatrickGotthard** [comment]
Hi @fschiettecatte,

the next release will support Java 8 again, I just merged https://github.com/rometools/rome/commit/01eb02b4f79bd4bed15904dd8ee3d29b4c7c6371

Regards
Patrick

**Comment by fschiettecatte** [comment]
Hi @PatrickGotthard

Awesome, thank you very much.

Cheers
François

**Pull request merged**
