### PR TITLE
Adds support for Atom person constructs to the Atom module

### PR DESCRIPTION
**Pull request by mpgirro**
[RFC 4287](https://tools.ietf.org/html/rfc4287) specifies *Person Constructs* in the Atom Syndication Format. These are used for the `atom:author` and `atom:contributor` elements. The ROME core appears to support these, but only for Atom feeds. Author/contributor elements provided in RSS feeds through the Atom namespace do not seem to be available through the `getAuthors()` and `getContributors()` methods of `SyndFeed` however.

This PR adds support for the extraction of Atom authors/contributors to the Atom module.

Unfortunately, the Atom module is currently named `AtomLink`, since it merely provides access to `atom:link` elements. It would have been possible to create a separate module for the Atom Person constructs, but this would have required separate parser and generator classes as well.  For a future major release, I therefore recommend to break the API and rename the module `AtomModule` to avoid confusion.

### CODE REVIEW

**Comment by snoopdave** [comment]
@mpgirro is this usage of Atom elements in RSS feeds a common use case that ROME should support? Are there some examples of this usage in RSS feeds provided by some popular services?

**Comment by mpgirro** [comment]
@snoopdave These Atom elements are regularly encountered in the RSS feeds of podcasts to describe the participants of an episode. Some examples of the most subscribed German feeds:

- <https://feeds.metaebene.me/cre/mp3>
- <https://feeds.metaebene.me/freakshow/m4a>
- <https://www.geschichte.fm/feed/mp3/>

Basically every feed generated by the very popular [Podlove Publisher](https://publisher.podlove.org) Podcast CMS has them, since the tools writes these elements into the feeds. Currently, it has [6000+](https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/) active installations.

**Comment by snoopdave** [comment]
Thanks @mpgirro. That's what we used to call "funky RSS". I plan to merge this shortly

**Comment by PatrickGotthard** [comment]
Version 1.16.0 is on its way to Maven Central.
It should be available soon.

**Pull request merged**
