### PR TITLE
Fix problems with invalid dates

### PR DESCRIPTION
**Pull request by nowheremanmail**
Current parser is not be able to handle invalid dates

### CODE REVIEW

**Comment by mishako** [comment]
@nowheremanmail 
Thanks for contribution!
Making date parser more lenient sounds like a good idea, but I'm not sure I understand why exactly you made certain changes. Would you mind explaining your thinking in the description of the commit or in the comments? For example, what is `masks[i].length() != 4` about? Why 4? Same with `sDate.indexOf('-') > 0 || sDate.length() == 4`.

**Comment by nowheremanmail** [comment]
Hi,
the point is one of the masks used (yyyy  the one with length = 4 ) failed (before my changes) with invalid dates like 20180716. It doesn't recognize invalid dates and returns impossible dates (year > 123123678) 

The second point is sDate.indexOf('-') is to recognize possible valid dates before add timezone

**Comment by mishako** [comment]
@nowheremanmail 
Thanks for the explanation!

Even with your changes `20180716` still gets parsed as year 20180716 though. So if your goal was to make `DateParser` fail on this kind of dates, it doesn't seem to work?

By doing `setLenient(false)` for the `yyyy` mask you make the date parser reject years past the max year (which for `java.util.GregorianCalendar` happens to be `292278994`). It looks like a somewhat arbitrary rule.

But even years after year `292278994` get successfully parsed if `T00:00GMT` is appended, so you added a condition to only append time to 4-character long dates. It does help to achieve what you want, but looks strange to me, because you seem to be using time concatenation for year filtering purposes.

Now, since the 4-character condition doesn't cover all dates that need `T00:00GMT` appended, you add `sDate.indexOf('-') > 0` condition, which I guess means "normal date"? Again, it works, because W3C dates have dashes, but isn't it a strange way to identify dates that don't match digits-only pattern?

**Comment by nowheremanmail** [comment]
Sorry I didn't know that yyyy mask must support years until 292278994, I've always thought this mask will be until year 9999!
Then I have to find another way to detect invalid dates

**Comment by PatrickGotthard** [comment]
Closing the pull request until there's a better solution :)

**Pull request closed without merging**
