### PR TITLE
GeoRSS Simple format parser enhancement

### PR DESCRIPTION
**Pull request by vplechnoy**
Added support to GeoRSS Simple format parser for:
- [x] Feature Type Tag -> <georss:featuretypetag>
- [x] Feature Name Tag -> <georss:featurename>
- [x] Relationship Tag -> <georss:relationshiptag>
- [x] Elevation -> <georss:elev> and <georss:floor>
- [x] Radius -> <georss:radius>

Added validating unit test

### CODE REVIEW

**Comment by vplechnoy** [comment]
Thank you, @hanoch, for reviewing !

**Comment by mishako** [comment]
:+1:

**Comment by vplechnoy** [comment]
Thank you, @mishako , for reviewing!

**Comment by mishako** [comment]
I will release a new version soon!

**Comment by hanoch** [comment]
thanks @mishako

**Comment by vplechnoy** [comment]
Thank you, @mishako , for heads up!

**Pull request merged**
