### PR TITLE
fix license headers

### PR DESCRIPTION
**Pull request by puntogil**
fix for https://github.com/rometools/rome/issues/288

### CODE REVIEW

**Comment by mishako** [comment]
Thanks for the help! Looks good, but I would like us to not add copyright lines. They are not necessary, but have to be retained forever if added. Since there are so many files to change, I prepared a command for you to remove copyrights. Run it on your branch.
```bash
git diff --name-only HEAD master | xargs sed -i '/Copyright 2004 Sun Microsystems/,+2d'
```

Also, could you please squash your commits into one? Thank you!

**Comment by puntogil** [comment]
Hi
With that command return: "sed: no input files"

**Comment by mishako** [comment]
Right, sorry, your branch is your master :). Replace `master` with `upstream/master` (if `upstream` is your remote for Rome).

**Comment by mishako** [comment]
Nice! Thanks. Could you please now squash all commits into one?

**Comment by puntogil** [comment]
Sorry, i don't understand your comment ....
https://github.com/rometools/rome/pull/289/commits/a3578be971b1b8c84670d2e796bb00db37fbb716 is not usable?

**Comment by mishako** [comment]
a3578be is usable, but it's not particularly easy to use it because you have 4 more commits in the same pull request. See, on top of this page it says:

> puntogil wants to merge **5 commits** into `rometools:master` from `puntogil:master`

It means that if I press "Merge pull request" button, I will merge 5 commits into the master branch. The problem is that those 4 additional commits are meaningless. We don't want meaningless commits to pollute the history.

Now, to fix it you can squash all 5 commits into one. It's easy to find a squashing tutorial on the internets. And, while you're at it, please don't mention "remove copyright" in the commit message. I mean, you aren't removing any copyrights, you don't add them. If I make sense :)

Happy gitting!

**Comment by puntogil** [comment]
open https://github.com/rometools/rome/pull/291

**Pull request closed without merging**
