### PR TITLE
Added Central Banking Module

### PR DESCRIPTION
**Pull request by bmunavar**
Changes to Support Central Banking Module @ http://www.cbwiki.net/wiki/index.php/RSS-CBMain

### CODE REVIEW

**Comment by PatrickGotthard** [comment]
Hi bmunavar,

would you like to explain, what the purpose of this module is? I think that rome-modules or a seperate module would be a better place for this extension because it is no "core" RSS/Atom format.

Regards,
Patrick

**Comment by bmunavar** [comment]
Hi Patrick,

Purpose of this Module is to support the Central Banking tags please refer the url @ http://www.cbwiki.net/wiki/index.php/RSS-CBMain

There are additional tags along with the basic ROME/Atom tags. This gave us an reason to add as CBModule like how we have DCModule in existing ROME Tools Project.

Central Banking RSS URLs are parsed using the Rome Tools and only CB tags were not handled, so we thought of contributing to it by adding additional CB Module.
Please refer the below RSS URL's which has CB tags.
@ http://www.bis.org/rss/

Thanks,
Munavar.

**Comment by nkiesel** [comment]
Hi Patrick,

as Munavar said, we simplytried to model the code along the lines of the "Dublin Core" module.  Perhaps that was wrong.  Could you explain a bit more how/where this CB module should live?  While most of the code is simply new files (and thus could be even moved into a separate JAR), some changes were doen to register the CB module.  So how wouldthat work if we separate the code?

**Comment by bmunavar** [comment]
Hi Patrick,

We were looking for your feedback and response related to CBModule check-ins we did.

Regards,
Munavar.

**Comment by PatrickGotthard** [comment]
Hi Norbert, hi Munavar,

sorry for the late response, I just relocated and have no internet so far. It would be great when the CB Module can be put in a seperate module but I don't know whether this is a problem (I don't know this part of the sourcecode well).

Could you explain, which changes prevent you from seperating the CB Module into a seperate JAR? Maybe we are able to find another solution.

Regards,
Patrick

**Comment by bmunavar** [comment]
Hi Patrick,

we can have CB Module as separate JAR, we just followed the 'DCModule' way.
Please help us with next steps how we can take it forward with the changes.

Regards,
Munavar.

**Comment by PatrickGotthard** [comment]
Hi @mishako,

would you like to have a look at this pull request? I think that DublinCore support was added directly to rome because it is very widely used. Do you also think that CentralBanking support should be added to rome-modules?

Regards,
Patrick

**Comment by PatrickGotthard** [comment]
I'll close this pull request because we have no resources to support an additional module.

**Pull request closed without merging**
