### PR TITLE
Fixes #326

### LINKED ISSUE #326: AtomLinkModuleImpl#setLink is broken since 1.7.1
Hello everybody,

The improvement with several links broke `#setLink`. If no link is set, calling `links.set(0, link);` leads to an `java.lang.IndexOutOfBoundsException`.

### PR DESCRIPTION
**Pull request by michael-simons**
TBH: I don't think that this is a good api evolution. What should setLink do now? Only set the first link (as it was tried to be implemented) or clear all and set a new? 

Anyway, I hope you find this fix useful.

### CODE REVIEW

**Comment by mishako** [comment]
Hi Michael, thanks for the fix! 👍 

Regarding the api evolution, I agree it's not perfect, but I'm not sure how we could have made it better. We had two requirements: support for multiple links and backwards compatibility. Although we could be more explicit about deprecation of `get/setLink` and undefined behavior when both `setLink` and `setLinks` are used.

Anyway, thank you for raising concern. It helps to get outside perspective. Please, keep it coming!

@PatrickGotthard One more PR to merge and patch version to release :)

**Comment by michael-simons** [comment]
You're welcome :) I like rometools and I have been using them a long time now. The least I can do!

**Comment by mishako** [comment]
@PatrickGotthard Maybe it's time to share the release key? It would be very convenient to be able to release a new version on my own.

Also, speaking of things to share, what is the plan for the `rometools.com` domain? It expires in October. Should we ask Martin to transfer the ownership and share it too?

**Comment by PatrickGotthard** [comment]
@mishako Sure, I'll collect what is needed need to be able to release new versions. Could you please ask Martin to prolongate the domain?

**Comment by imk** [comment]
A little bit out of scope of this pr, but: sorry for being inactive for such a long time, too many different projects competing with each other. About the domain, it's extended automatically, so there's nothing to take care about. Of course, I can transfer it if you prefer being in control, but there's no need (for my part).

**Comment by mishako** [comment]
@imk Happy to hear that the domain is taken care of. No need for transfer then!

**Comment by mishako** [comment]
The version with this change (1.7.2) is now finally released. Patrick is looking into streamlining the release process.

**Comment by michael-simons** [comment]
Nice. Thanks for including this!

**Pull request merged**
