### PR TITLE
Added: Http URL Redirect check (Status Code 30x) to follow to a new location

### PR DESCRIPTION
**Pull request by nea**
Hi there

I am suggesting this PR to adapt the XMLReader to double-check the URL connection for a redirect request/status (30x). If so, following to that location before parsing the data which would result in errors. A
```
HttpURLConnection.setFollowRedirects(true);
```
or
```
con.setInstanceFollowRedirects(true);
```
does not work on its own.

This is an initial suggestion as I faced that problem. I am open for any feedback or changes but would love to see such a functionality.

Cheers

### CODE REVIEW

**Comment by snoopdave** [comment]
This looks pretty good, have you tested it and does it work well?

Is there any way we can have a JUnit test for this?  (I don't think we have any way to "mock" an HTTP server in the ROME testing setup.

**Comment by nea** [comment]
Hi

Yes, I am using my custom branch https://github.com/nea/rome with that exact change on a system of mine (why I first stumbled upon it).

A Test... sure thing. Will see to it as soon as I have time.


Best

**Comment by mishako** [comment]
@nea Do you refer to URLConnection's cross-protocol redirect issue[1]? I mean `setFollowRedirects(true)` does work on it's own, at least for http-to-http redirects.

[1] http://stackoverflow.com/questions/1884230/java-doesnt-follow-redirect-in-urlconnection

**Comment by mishako** [comment]
BTW there is a good mock HTTP server: https://github.com/jamesdbloom/mockserver
It's really easy to use: https://gist.github.com/mishako/23af30ee6409a991714e

**Comment by nea** [comment]
Hi

I will check on the Mockserver... that looks nice actually.
My case was a protocol change.


Cheers

**Comment by mishako** [comment]
Things I don't like in this implementation (not saying everything has to be fixed):
 * It handles only single redirect, i.e. redirect chain http->https->http will fail.
 * Caller of the class loses control over the connection, because we're creating a new object. That is connection timeout as set here[1] will not apply to the redirected connection.
 * It would benefit from the extract method refactoring.
 * Most comments are redundant or could be made redundant by extracting a method.
 * Obviously code formatting.

[1] https://github.com/ryuichiokubo/TheHome/blob/045256fbd4b9039e982d30f4cc9017a492401aa2/src/thehome/TheHomeServlet.java

**Comment by mishako** [comment]
@nea Any thoughts?

**Comment by nea** [comment]
Hey

I am currently up in work so I won't have much time before Christmas to tackle this. You got valid points and I want to check into them as soon as I found the space.

Sorry for the silence

**Comment by mishako** [comment]
No activity on this pull request for half a year, closing it. New pull request can be submitted when ready.

**Pull request closed without merging**
